### ISSUE TITLE
generate_report.py throwing KeyError

### ISSUE THREAD

**Issue by shivpal** [simonwongwong/Facebook-Messenger-Statistics#19]
I am running this on a Windows 10 laptop against recently downloaded facebook files. It throws the exception below. Any ideas what the issue here might be? Thanks!

Traceback (most recent call last):
  File "<my dir>\Facebook-Messenger-Statistics-master\generate_report.py", line 51, in <module>
    yearly_graph, monthly_graph, hourly_graph, minutely_graph, daily_graph, weekday_graph = cs.time_stats(show=False)
  File "<my dir>\Facebook-Messenger-Statistics-master\chatstat.py", line 15, in wrapper
    fig, graph = graph_func(*args, **kwargs)
  File "<my dir>\Facebook-Messenger-Statistics-master\chatstat.py", line 427, in time_stats
    time_indexed = self.generate_time_indexed_df(messages)
  File "<my dir>\Facebook-Messenger-Statistics-master\chatstat.py", line 281, in generate_time_indexed_df
    time_indexed = messages.set_index('timestamp_ms')
  File "<my home dir>\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 4727, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['timestamp_ms'] are in the columns"

**Comment by simonwongwong** [comment]
Hmm, it's possible that Facebook changed the data format for their exports. I haven't tried using this in a while. I will take a look

**Comment by shivpal** [comment]
Thanks Simon. LMK if you need me to send you a couple of JSON files that I am using.
