### ISSUE TITLE
Attribute 'msg' is missing

### ISSUE THREAD

**Issue by adaxiik** [simonwongwong/Facebook-Messenger-Statistics#20]
Error while generating report :

Parsing data from C:/Users/xxx/Desktop/messages
Traceback (most recent call last):
  File "generate_report.py", line 45, in <module>
    how.add_trace(cs.msg_types(show=False), row=1, col=1)
  File "C:\Users\xxx\Desktop\Facebook-Messenger-Statistics-master\chatstat.py", line 15, in wrapper
    fig, graph = graph_func(*args, **kwargs)
  File "C:\Users\xxx\Desktop\Facebook-Messenger-Statistics-master\chatstat.py", line 149, in msg_types
    type_dict = {"type": {"stickers": chat.sticker.count(), "photos": chat.photos.count(), "videos": chat.videos.count(), "links": chat[[("http" in str(msg)) for msg in chat.msg]].msg.count()}}
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'msg'

**Comment by adaxiik** [comment]
My bad. I used the /messages folder instead of /inbox ..

There could be error handling for this 😅
